[package]
name = "b2cli"
version = "0.1.0"
authors = ["Alice Ryhl <alice@ryhl.io>"]

[dependencies]
backblaze-b2 = "0.1.9-2"
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
clap = "~2.19.0"
serde = "1"
serde_json = "1"
sha1 = "0.2.0"
